### PR TITLE
Derived data with polar calculations.

### PR DESCRIPTION
**Pull request by ieb**
This pull request adds polar performance calculations. It needs review since some of the keys may not be 100% correct, however it seems to work for me and flows through to other modules. At the moment the polar data is in javascript, which may not be suitable for everyone.

Doing the pull request as it was asked for at https://groups.google.com/forum/#!topic/signalk/YpmDpfv-Ro4

### CODE REVIEW

**Comment by sbender9** [comment]
I'm sorry @ieb , but there are too many things combined into to this one pull request. Many not related at all to the title of the PR. Do you have time to separate this into well defined PR's?

**Comment by sbender9** [comment]
We can't include the polar data in the plugin code. It would need to come from somewhere else.

**Comment by sbender9** [comment]
@joabakk aren't you doing things with polar data? Are there conflicts here or points of integration?

**Comment by tkurki** [comment]
Well, now that we have some code that uses polar tables it is time to get polar data representation in the model in shape and create a webapp/plugin combo that allows you to enter, edit and visualise polar data and use it. Sounds awfully much like a signalk-polars plugin to me, based on work here and discussions at https://github.com/SignalK/specification/pull/360.

**Comment by ieb** [comment]
@sbender9 I agree, although to get the performance calcs working on my boat I needed everything other than cogMagnetic. I needed that because the COG sentence needed it.
The polar representation is pretty standard as used in most other systems, Expedition, NKE, SailGribWR. It might be better in CSV form if you want users to be able to edit it, but putting CSV into json (which is almost what I had) is relatively trivial.
In most routing I have done, I have dealt with sea state separately as it's too hard predict sea state as that depends on the weather model for 1000s of miles around, not just the current wind, and its highly unpredictable.
Since someone else is already working on performance calculations it doesnt make sense to merge this pull request. TBH, I am not 100% certain everything is correct, and I still get results out a sea I dont always believe when it comes to the optimal angles.

@tkurki without the output of the derived data produced from the performance calculation the PNKE wont work, and some of the ones in the TODO area might not work at all. You might want to drop those from the  NMEA0183 pull request I did as they are bound to generate unnecessary noise from anyone wanting to drive the NKE Android app for real.

I will keep developing and correcting the branch in the repo where this came from. Thank you all for the pointer to derived data and other help.

**Comment by joabakk** [comment]
I have made a plugin and webapp pair for polar diagrams. This predates derived-data and https://github.com/SignalK/specification/issues/359. The plugin (https://github.com/joabakk/signalk-polar) does the calculations, submits the dynamic values that exist(ed) in the schema to the server and stores the polar table in mysql. The webapp , https://github.com/joabakk/signalk-polar-graphing picks this table up and (as far as I recall) presents the diagram via html. 
It may or may not make sense to put some of the polar calculations into derived-data. Don't give up just yes @ieb!

**Comment by ieb** [comment]
The Highcharts polar looks interesting. I had previously done that with
d3js. I thought highcharts required a license which was a bit $$ ? Or is
there an open source version ?

**Comment by joabakk** [comment]
Eh licence? It's on npm. Reading more thoroughly "The Highsoft Standard Terms and Conditions applies if you run a commercial or governmental website, intranet or project". The way I read it, we are good

**Comment by ieb** [comment]
If you can sign up for the personal use license with no commercial and no
redistribution, you'r ok. Anyone else will need to do the same.
See https://shop.highsoft.com/highcharts#non-com and search for
redistribution in the T&Cs

There are many GitHub and npm projects that look like opensource, but have
commercial licensing terms. Even the React license has a little facebook
trap in it. Generally it if MIT, BSD or Apache your 100% safe. But then I
am biased see https://www.apache.org/foundation/members.html

**Comment by joabakk** [comment]
Thanks @ieb for the pointer. I have signed up and informed as they require now

**Pull request closed without merging**
