### PR TITLE
True Wind when we do not have Log Speed

### PR DESCRIPTION
**Pull request by netAction**

### CODE REVIEW

**Comment by sbender9** [comment]
This is ground wind. It's already there.

**Comment by tkurki** [comment]
This is based on sog, not stw.

**Comment by sbender9** [comment]
Yes, that's called ground wind: https://github.com/sbender9/signalk-derived-data/blob/master/calcs/groundWind.js

**Comment by tkurki** [comment]
Oops, my mistake.

**Comment by netAction** [comment]
Yes, both this and *groundWind.js* use AWS, AWA, COG and SOG.

This returns wind direction over ground, useful for displays. Plus TWS and TWA which you need in wind gauges.

*groundWind.js* returns wind speed over ground and wind direction relative to heading. Don't know where you need them.

You are right, wind direction relative to heading is the same as TWA, but the returned variable names are all different.

**Comment by sbender9** [comment]
Sorry, you can't calculate TWA or TWS without STW. It should not be here.

If you need wind direction over ground, you should add that to groundWind.js.

**Comment by netAction** [comment]
The whole pull request is about a fallback for the case that STW fails and we need to set STW=SOG.

In the derived data plugin there maybe should be a switch for this case. I tried stacking multiple calcs and it did not work. So I chose to calculate TWS and TWA directly.

**Comment by sbender9** [comment]
I don't like the idea of putting data into SignalK that claims to one thing, but is something else.

Why wouldn't you just use the correct paths to display GWS and GWA on the client if TWA and TWS are not available?

**Comment by netAction** [comment]
Good question. This would be an issue for all wind gauges.

**Pull request closed without merging**
